/*
 * EXIT_INT_Configurations.h
 *
 *  Created on: Oct 23, 2023
 *      Author: mtoty
 */

#ifndef MCAL_EXIT_INT_DRIVER_NTI_EXIT_INT_CONFIGURATIONS_H_
#define MCAL_EXIT_INT_DRIVER_NTI_EXIT_INT_CONFIGURATIONS_H_



#endif /* MCAL_EXIT_INT_DRIVER_NTI_EXIT_INT_CONFIGURATIONS_H_ */
